name: CI/CD for React + Vite + Netlify

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # Optional: Add tests here if needed
      # - name: Run Tests
      #   run: npm test

      - name: Deploy to Netlify (production only)
        if: github.ref == 'refs/heads/main'
        uses: nwtgck/actions-netlify@v2.0.0
        with:
          publish-dir: "./dist"
          production-deploy: true
          deploy-message: "Deployed via GitHub Actions"
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
